name: Release

on:
  push:
    tags:
      - '*.*.*'
jobs:
  build:
    runs-on: ${{ matrix.os }}
    environment: package
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest ]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 20
        uses: actions/setup-node@v3
        with:
          node-version: "20.x"
      - name: Install
        run: npm ci

      - name: Build
        run: |
          if [ "$RUNNER_OS" = "Windows" ]; then
            npm run build --cmd
          else
            npm run build
          fi
        env:
          GH_TOKEN: ${{ secrets.actions }}

      # step5: 清理
      - name: Cleanup artifacts
        run: |
          if [ "$RUNNER_OS" = "Windows" ]; then
            Get-ChildItem -Path "release" -Exclude *.AppImage, *.tar.gz, *.zip | Remove-Item -Force -Recurse
          else
            npx rimraf "release/^!(*.AppImage|*.tar.gz|*.zip)"
          fi

      # step6: 上传
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.os }}
          path: release

      # step7: 发布
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: "release/**"
        env:
          GITHUB_TOKEN: ${{ secrets.actions }}
